version: "3.5"

services:

  php:
    build: dockerfiles/php
    working_dir: "/var/www/app"
    volumes:
      - "m:\\apps\\game_of_life\\:/var/www/app"
    environment:
      PHP_IDE_CONFIG: serverName=game_of_life
      XDEBUG_CONFIG: remote_host=172.30.39.145
